global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - follow_redirects: true
    enable_http2: true
    scheme: http
    timeout: 10s
    api_version: v2
    static_configs:
    - targets: []
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - localhost:9090
- job_name: nodered
  honor_timestamps: true
  scrape_interval: 5s
  scrape_timeout: 5s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - mynodered1:1880global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - follow_redirects: true
    enable_http2: true
    scheme: http
    timeout: 10s
    api_version: v2
    static_configs:
    - targets: []
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - localhost:9090
- job_name: dat
  honor_timestamps: true
  scrape_interval: 5s
  scrape_timeout: 5s
  metrics_path: /metrics/dat
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - mynodered1:1880
- job_name: stat
  honor_timestamps: true
  scrape_interval: 60s
  scrape_timeout: 5s
  metrics_path: /metrics/stat
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - mynodered1:1880
- job_name: cpu
  honor_timestamps: true
  scrape_interval: 60s
  scrape_timeout: 5s
  metrics_path: /metrics/cpu
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - mynodered1:1880
- job_name: linux
  honor_timestamps: true
  scrape_interval: 60s
  scrape_timeout: 5s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - host.docker.internal:9100
