{
 "title": "HIU Data",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "node", "query": "fulhamrs1,fulhamrs2" },
   {
    "name": "HIU",
    "query": "SELECT value FROM readings WHERE node='$node' AND varkey='Serial'"
   },
   {
    "name": "upTime",
    "query": "SELECT value FROM readings WHERE node='$node' AND varkey='upTime'"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Primary DP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT t1.varkey, t2.title, t1.value::numeric, t2.units FROM readings t1\r\n  INNER JOIN fields t2 ON t1.varkey = t2.varkey AND t1.vargroup = t2.vargroup\r\n  WHERE (t1.varkey = 'dpH') AND t1.node = '$node' AND t1.device = '$HIU'\r\n  ORDER BY t1.varkey"
    }
   ]
  },
  {
   "title": "Primary Temp",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT t1.varkey, t2.title, t1.value::numeric, t2.units FROM readings t1\r\n  INNER JOIN fields t2 ON t1.varkey = t2.varkey AND t1.vargroup = t2.vargroup\r\n  WHERE (t1.varkey = 'tH') AND t1.node = '$node' AND t1.device = '$HIU'\r\n  ORDER BY t1.varkey"
    }
   ]
  },
  {
   "title": "DHW Flow",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT t1.varkey, t2.title, t1.value::numeric, t1.timestamp AS time, t2.units FROM readings t1\r\n  INNER JOIN fields t2 ON t1.varkey = t2.varkey AND t1.vargroup = t2.vargroup\r\n  WHERE (t1.varkey = 'fC' OR t1.varkey = 'xDHW' OR t1.varkey = 'fHDHW') AND t1.node = '$node' AND t1.device = '$HIU'\r\n  ORDER BY t1.varkey"
    }
   ]
  },
  {
   "title": "DHW Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "DHW Output Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/$node/",
     "query": "import \"strings\"\r\nfrom(bucket: \"$bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"varkey\"] == \"tCHo\" or r[\"varkey\"] == \"tHoCH\")\r\n  |> filter(\r\n          fn: (r) => if \"$node\" != \"*\" then\r\n                        r[\"node\"] == \"$node\"\r\n                    else\r\n                        r._measurement != \"\",\r\n      )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({r with device: strings.joinStr(arr: [r[\"node\"], r[\"device\"], r[\"varkey\"]], v: \"-\")}))\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "dat_tCo" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Primary Return Temperature DHW",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "/$node/",
     "query": "import \"strings\"\r\nfrom(bucket: \"$bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"varkey\"] == \"tCHo\" or r[\"varkey\"] == \"tHoCH\")\r\n  |> filter(\r\n          fn: (r) => if \"$node\" != \"*\" then\r\n                        r[\"node\"] == \"$node\"\r\n                    else\r\n                        r._measurement != \"\",\r\n      )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({r with device: strings.joinStr(arr: [r[\"node\"], r[\"device\"], r[\"varkey\"]], v: \"-\")}))\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "dat_tHoDHW" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "DHW Return Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "/$node/",
     "query": "import \"strings\"\r\nfrom(bucket: \"$bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"varkey\"] == \"tCHo\" or r[\"varkey\"] == \"tHoCH\")\r\n  |> filter(\r\n          fn: (r) => if \"$node\" != \"*\" then\r\n                        r[\"node\"] == \"$node\"\r\n                    else\r\n                        r._measurement != \"\",\r\n      )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({r with device: strings.joinStr(arr: [r[\"node\"], r[\"device\"], r[\"varkey\"]], v: \"-\")}))\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "dat_tDHWReturn" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "DHW Settings",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT t1.varkey, t2.title, t1.value, t2.units FROM readings t1\r\n  INNER JOIN fields t2 ON t1.varkey = t2.varkey AND t1.vargroup = t2.vargroup\r\n  WHERE (t1.vargroup = 'settings') AND t1.node = '$node' AND t1.device = '$HIU'\r\n  ORDER BY t1.varkey"
    }
   ]
  },
  {
   "title": "DHW Temperatures",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH \r\ndhw1 AS (SELECT t1.node, t1.device, t1.vargroup, t1.varkey, t2.title, t1.value::numeric, t2.units FROM readings t1\r\n  INNER JOIN fields t2 ON t1.varkey = t2.varkey AND t1.vargroup = t2.vargroup\r\n  WHERE (t1.varkey = 'tCo') AND t1.node = '$node' AND t1.vargroup = 'dat' AND (t1.device = '$HIU' OR t1.device = 'dhw')\r\n  ORDER BY t1.varkey\r\n),\r\ndhw2 AS (SELECT d1.*, t3.value::numeric AS flowRate,\r\n       CASE WHEN t3.value::numeric=0 THEN 'white'\r\n            ELSE 'green'\r\n       END\r\n     FROM dhw1 d1 \r\n  INNER JOIN readings t3 ON d1.node = t3.node AND d1.device = t3.device AND d1.vargroup = t3.vargroup AND t3.varkey = 'fC'\r\n)\r\nSELECT * FROM dhw2;"
    },
    {
     "rawSql": "WITH \r\ndhw1 AS (SELECT t1.node, t1.device, t1.vargroup, t1.varkey, t2.title, t1.value::numeric, t2.units FROM readings t1\r\n  INNER JOIN fields t2 ON t1.varkey = t2.varkey AND t1.vargroup = t2.vargroup\r\n  WHERE (t1.varkey = 'tHoDHW') AND t1.node = '$node' AND t1.vargroup = 'dat' AND (t1.device = '$HIU' OR t1.device = 'dhw')\r\n  ORDER BY t1.varkey\r\n),\r\ndhw2 AS (SELECT d1.*, t3.value::numeric AS flowRate,\r\n       CASE WHEN t3.value::numeric<6 THEN 'white'\r\n            ELSE 'green'\r\n       END\r\n     FROM dhw1 d1 \r\n  INNER JOIN readings t3 ON d1.node = t3.node AND d1.device = t3.device AND d1.vargroup = t3.vargroup AND t3.varkey = 'xDHW'\r\n)\r\nSELECT * FROM dhw2;"
    },
    {
     "rawSql": "SELECT t1.varkey, t2.title, t1.value::numeric, t2.units FROM readings t1\r\n  INNER JOIN fields t2 ON t1.varkey = t2.varkey AND t1.vargroup = t2.vargroup\r\n  WHERE (t1.varkey = 'tDHWReturn') AND t1.node = '$node' AND t1.vargroup = 'dat' AND (t1.device = '$HIU' OR t1.device = 'dhw')\r\n  ORDER BY t1.varkey"
    }
   ]
  },
  {
   "title": "Last Tap Delivery",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT t1.varkey, t2.title, t1.value::numeric, t2.units FROM readings t1\r\n  INNER JOIN fields t2 ON t1.varkey = t2.varkey AND t1.vargroup = t2.vargroup\r\n  WHERE (t1.varkey = 'lasttCo' OR t1.varkey = 'lastvCrun' OR t1.varkey = 'lastvCavr') AND t1.node = '$node' AND (t1.device = '$HIU' OR t1.device = 'dhw')\r\n  ORDER BY t1.varkey"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "flowlpm" } },
   "targets": [
    {
     "alias": "DHW Flow Rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/$node/",
     "query": "import \"strings\"\r\nfrom(bucket: \"$bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"varkey\"] == \"fC\")\r\n  |> filter(\r\n          fn: (r) => if \"$node\" != \"*\" then\r\n                        r[\"node\"] == \"$node\"\r\n                    else\r\n                        r._measurement != \"\",\r\n      )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({r with device: strings.joinStr(arr: [r[\"node\"], r[\"device\"], r[\"varkey\"]], v: \"-\")}))\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "dat_fC" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CH Settings",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT t1.varkey, t2.title, t1.value, t2.units FROM readings t1\r\n  INNER JOIN fields t2 ON t1.varkey = t2.varkey AND t1.vargroup = t2.vargroup\r\n  WHERE (t1.vargroup = 'settings') AND t1.node = '$node' AND t1.device = '$HIU'\r\n  ORDER BY t1.varkey"
    }
   ]
  },
  {
   "title": "CH Demand",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT t1.varkey, t2.title, t1.value::numeric, t2.units FROM readings t1\r\n  INNER JOIN fields t2 ON t1.varkey = t2.varkey AND t1.vargroup = t2.vargroup\r\n  WHERE (t1.varkey = 'stat' OR t1.varkey = 'pump') AND t1.node = '$node' AND t1.device = '$HIU'\r\n  ORDER BY t1.varkey"
    }
   ]
  },
  {
   "title": "CH Flow",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT t1.varkey, t2.title, t1.value::numeric, t2.units FROM readings t1\r\n  INNER JOIN fields t2 ON t1.varkey = t2.varkey AND t1.vargroup = t2.vargroup\r\n  WHERE (t1.varkey = 'fHCH' OR t1.varkey = 'xCH') AND t1.node = '$node' AND t1.device = '$HIU'\r\n  ORDER BY t1.varkey"
    }
   ]
  },
  {
   "title": "Central Heating Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "CH Output Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/$node/",
     "query": "import \"strings\"\r\nfrom(bucket: \"$bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"varkey\"] == \"tCHo\" or r[\"varkey\"] == \"tHoCH\")\r\n  |> filter(\r\n          fn: (r) => if \"$node\" != \"*\" then\r\n                        r[\"node\"] == \"$node\"\r\n                    else\r\n                        r._measurement != \"\",\r\n      )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({r with device: strings.joinStr(arr: [r[\"node\"], r[\"device\"], r[\"varkey\"]], v: \"-\")}))\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "dat_tCHo" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "node::tag", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "Primary Return Temperature CH",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "/$node/",
     "query": "import \"strings\"\r\nfrom(bucket: \"$bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"varkey\"] == \"tCHo\" or r[\"varkey\"] == \"tHoCH\")\r\n  |> filter(\r\n          fn: (r) => if \"$node\" != \"*\" then\r\n                        r[\"node\"] == \"$node\"\r\n                    else\r\n                        r._measurement != \"\",\r\n      )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({r with device: strings.joinStr(arr: [r[\"node\"], r[\"device\"], r[\"varkey\"]], v: \"-\")}))\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "dat_tHoCH" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Pump",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "/$node/",
     "query": "import \"strings\"\r\nfrom(bucket: \"$bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"varkey\"] == \"tCHo\" or r[\"varkey\"] == \"tHoCH\")\r\n  |> filter(\r\n          fn: (r) => if \"$node\" != \"*\" then\r\n                        r[\"node\"] == \"$node\"\r\n                    else\r\n                        r._measurement != \"\",\r\n      )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({r with device: strings.joinStr(arr: [r[\"node\"], r[\"device\"], r[\"varkey\"]], v: \"-\")}))\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "dat_pump" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CH Temperatures",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH \r\ndhw1 AS (SELECT t1.node, t1.device, t1.vargroup, t1.varkey, t2.title, t1.value::numeric, t2.units FROM readings t1\r\n  INNER JOIN fields t2 ON t1.varkey = t2.varkey AND t1.vargroup = t2.vargroup\r\n  WHERE (t1.varkey = 'tCHo') AND t1.node = '$node' AND t1.vargroup = 'dat' AND (t1.device = '$HIU' OR t1.device = 'dhw')\r\n  ORDER BY t1.varkey\r\n),\r\ndhw2 AS (SELECT d1.*, t3.value::numeric AS flowRate,\r\n       CASE WHEN t3.value::numeric=0 THEN 'white'\r\n            ELSE 'green'\r\n       END\r\n     FROM dhw1 d1 \r\n  INNER JOIN readings t3 ON d1.node = t3.node AND d1.device = t3.device AND d1.vargroup = t3.vargroup AND t3.varkey = 'pump'\r\n)\r\nSELECT * FROM dhw2;"
    },
    {
     "rawSql": "WITH \r\ndhw1 AS (SELECT t1.node, t1.device, t1.vargroup, t1.varkey, t2.title, t1.value::numeric, t2.units FROM readings t1\r\n  INNER JOIN fields t2 ON t1.varkey = t2.varkey AND t1.vargroup = t2.vargroup\r\n  WHERE (t1.varkey = 'tHoCH') AND t1.node = '$node' AND t1.vargroup = 'dat' AND (t1.device = '$HIU' OR t1.device = 'dhw')\r\n  ORDER BY t1.varkey\r\n),\r\ndhw2 AS (SELECT d1.*, t3.value::numeric AS flowRate,\r\n       CASE WHEN d1.value::numeric>55 THEN 'red'\r\n            WHEN d1.value::numeric>50 THEN 'yellow'\r\n            WHEN t3.value::numeric>5 THEN 'green'            \r\n            ELSE 'white'\r\n       END\r\n     FROM dhw1 d1 \r\n  INNER JOIN readings t3 ON d1.node = t3.node AND d1.device = t3.device AND d1.vargroup = t3.vargroup AND t3.varkey = 'xCH'\r\n)\r\nSELECT * FROM dhw2;"
    }
   ]
  },
  {
   "title": "CH Pressure",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT t1.varkey, t2.title, t1.value::numeric, t2.units FROM readings t1\r\n  INNER JOIN fields t2 ON t1.varkey = t2.varkey AND t1.vargroup = t2.vargroup\r\n  WHERE (t1.varkey = 'pCH') AND t1.node = '$node' AND t1.device = '$HIU'\r\n  ORDER BY t1.varkey"
    }
   ]
  },
  {
   "title": "Graphics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "$HIU",
     "type": "canvas",
     "gridPos": { "h": 17, "w": 17, "x": 0, "y": 22 },
     "targets": [
      {
       "rawSql": "SELECT t1.varkey, t2.title, t1.value, t2.units FROM readings t1\r\n  INNER JOIN fields t2 ON t1.varkey = t2.varkey AND t1.vargroup = t2.vargroup\r\n  WHERE t1.node = '$node'AND t1.device = '$HIU'\r\n  ORDER BY t1.varkey"
      }
     ]
    },
    {
     "title": "HIU Serial Number",
     "type": "stat",
     "gridPos": { "h": 3, "w": 7, "x": 17, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT t1.varkey, t2.title, t1.value, t2.units FROM readings t1\r\n  INNER JOIN fields t2 ON t1.varkey = t2.varkey AND t1.vargroup = t2.vargroup\r\n  WHERE (t1.varkey = 'Serial') AND t1.node = '$node' AND t1.device = '$HIU'\r\n  ORDER BY t1.varkey"
      }
     ]
    },
    {
     "title": "Up Time",
     "type": "stat",
     "gridPos": { "h": 3, "w": 7, "x": 17, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT t1.varkey, t2.title, t1.value, t2.units FROM readings t1\r\n  INNER JOIN fields t2 ON t1.varkey = t2.varkey AND t1.vargroup = t2.vargroup\r\n  WHERE (t1.varkey = 'upTime') AND t1.node = '$node'\r\n  ORDER BY t1.varkey"
      }
     ]
    }
   ]
  },
  {
   "title": "Current Values",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "CH Settings",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT t1.varkey, t2.title, t1.value, t2.units FROM readings t1\r\n  INNER JOIN fields t2 ON t1.varkey = t2.varkey AND t1.vargroup = t2.vargroup\r\n  WHERE (t1.vargroup = 'settings') AND t1.node = '$node' AND t1.device = '$HIU'\r\n  ORDER BY t1.varkey"
      }
     ]
    },
    {
     "title": "CH Demand",
     "type": "stat",
     "gridPos": { "h": 5, "w": 2, "x": 4, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT t1.varkey, t2.title, t1.value::numeric, t2.units FROM readings t1\r\n  INNER JOIN fields t2 ON t1.varkey = t2.varkey AND t1.vargroup = t2.vargroup\r\n  WHERE (t1.varkey = 'stat' OR t1.varkey = 'pump') AND t1.node = '$node' AND t1.device = '$HIU'\r\n  ORDER BY t1.varkey"
      }
     ]
    },
    {
     "title": "CH Flow",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT t1.varkey, t2.title, t1.value::numeric, t2.units FROM readings t1\r\n  INNER JOIN fields t2 ON t1.varkey = t2.varkey AND t1.vargroup = t2.vargroup\r\n  WHERE (t1.varkey = 'fHCH' OR t1.varkey = 'xCH') AND t1.node = '$node' AND t1.device = '$HIU'\r\n  ORDER BY t1.varkey"
      }
     ]
    },
    {
     "title": "DHW Settings",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT t1.varkey, t2.title, t1.value, t2.units FROM readings t1\r\n  INNER JOIN fields t2 ON t1.varkey = t2.varkey AND t1.vargroup = t2.vargroup\r\n  WHERE (t1.vargroup = 'settings') AND t1.node = '$node' AND t1.device = '$HIU'\r\n  ORDER BY t1.varkey"
      }
     ]
    },
    {
     "title": "DHW Flow",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT t1.varkey, t2.title, t1.value::numeric, t1.timestamp AS time, t2.units FROM readings t1\r\n  INNER JOIN fields t2 ON t1.varkey = t2.varkey AND t1.vargroup = t2.vargroup\r\n  WHERE (t1.varkey = 'fC' OR t1.varkey = 'xDHW' OR t1.varkey = 'fHDHW') AND t1.node = '$node' AND t1.device = '$HIU'\r\n  ORDER BY t1.varkey"
      }
     ]
    },
    {
     "title": "CH Temperatures",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT t1.varkey, t2.title, t1.value::numeric, t2.units FROM readings t1\r\n  INNER JOIN fields t2 ON t1.varkey = t2.varkey AND t1.vargroup = t2.vargroup\r\n  WHERE (t1.varkey = 'tCHo' OR t1.varkey = 'tHoCH') AND t1.node = '$node' AND t1.device = '$HIU'\r\n  ORDER BY t1.varkey"
      }
     ]
    },
    {
     "title": "DHW Temperatures",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT t1.varkey, t2.title, t1.value::numeric, t2.units FROM readings t1\r\n  INNER JOIN fields t2 ON t1.varkey = t2.varkey AND t1.vargroup = t2.vargroup\r\n  WHERE (t1.varkey = 'tCo' OR t1.varkey = 'tHoDHW' OR t1.varkey = 'tDHWReturn') AND t1.node = '$node' AND t1.vargroup = 'dat' AND (t1.device = '$HIU' OR t1.device = 'dhw')\r\n  ORDER BY t1.varkey"
      }
     ]
    },
    {
     "title": "CH Pressure",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 4, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT t1.varkey, t2.title, t1.value::numeric, t2.units FROM readings t1\r\n  INNER JOIN fields t2 ON t1.varkey = t2.varkey AND t1.vargroup = t2.vargroup\r\n  WHERE (t1.varkey = 'pCH') AND t1.node = '$node' AND t1.device = '$HIU'\r\n  ORDER BY t1.varkey"
      }
     ]
    }
   ]
  },
  {
   "title": "Operation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Central Heating Temperatures",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "alias": "CH Output Temperature",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "/$node/",
       "query": "import \"strings\"\r\nfrom(bucket: \"$bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"varkey\"] == \"tCHo\" or r[\"varkey\"] == \"tHoCH\")\r\n  |> filter(\r\n          fn: (r) => if \"$node\" != \"*\" then\r\n                        r[\"node\"] == \"$node\"\r\n                    else\r\n                        r._measurement != \"\",\r\n      )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({r with device: strings.joinStr(arr: [r[\"node\"], r[\"device\"], r[\"varkey\"]], v: \"-\")}))\r\n  |> yield(name: \"last\")",
       "select": [
        [
         { "params": [ "dat_tCHo" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "node::tag", "operator": "=~", "value": "/^$node$/" }
       ]
      },
      {
       "alias": "Primary Return Temperature CH",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "/$node/",
       "query": "import \"strings\"\r\nfrom(bucket: \"$bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"varkey\"] == \"tCHo\" or r[\"varkey\"] == \"tHoCH\")\r\n  |> filter(\r\n          fn: (r) => if \"$node\" != \"*\" then\r\n                        r[\"node\"] == \"$node\"\r\n                    else\r\n                        r._measurement != \"\",\r\n      )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({r with device: strings.joinStr(arr: [r[\"node\"], r[\"device\"], r[\"varkey\"]], v: \"-\")}))\r\n  |> yield(name: \"last\")",
       "select": [
        [
         { "params": [ "dat_tHoCH" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "DHW Temperatures",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "alias": "DHW Output Temperature",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "/$node/",
       "query": "import \"strings\"\r\nfrom(bucket: \"$bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"varkey\"] == \"tCHo\" or r[\"varkey\"] == \"tHoCH\")\r\n  |> filter(\r\n          fn: (r) => if \"$node\" != \"*\" then\r\n                        r[\"node\"] == \"$node\"\r\n                    else\r\n                        r._measurement != \"\",\r\n      )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({r with device: strings.joinStr(arr: [r[\"node\"], r[\"device\"], r[\"varkey\"]], v: \"-\")}))\r\n  |> yield(name: \"last\")",
       "select": [
        [
         { "params": [ "dat_tCo" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Primary Return Temperature DHW",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "/$node/",
       "query": "import \"strings\"\r\nfrom(bucket: \"$bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"varkey\"] == \"tCHo\" or r[\"varkey\"] == \"tHoCH\")\r\n  |> filter(\r\n          fn: (r) => if \"$node\" != \"*\" then\r\n                        r[\"node\"] == \"$node\"\r\n                    else\r\n                        r._measurement != \"\",\r\n      )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({r with device: strings.joinStr(arr: [r[\"node\"], r[\"device\"], r[\"varkey\"]], v: \"-\")}))\r\n  |> yield(name: \"last\")",
       "select": [
        [
         { "params": [ "dat_tHoDHW" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "DHW Return Temperature",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "/$node/",
       "query": "import \"strings\"\r\nfrom(bucket: \"$bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"varkey\"] == \"tCHo\" or r[\"varkey\"] == \"tHoCH\")\r\n  |> filter(\r\n          fn: (r) => if \"$node\" != \"*\" then\r\n                        r[\"node\"] == \"$node\"\r\n                    else\r\n                        r._measurement != \"\",\r\n      )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({r with device: strings.joinStr(arr: [r[\"node\"], r[\"device\"], r[\"varkey\"]], v: \"-\")}))\r\n  |> yield(name: \"last\")",
       "select": [
        [
         { "params": [ "dat_tDHWReturn" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Demand",
     "type": "state-timeline",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "Stat",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "/$node/",
       "query": "import \"strings\"\r\nfrom(bucket: \"$bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"varkey\"] == \"stat\" or r[\"varkey\"] == \"pump\")\r\n  |> filter(\r\n          fn: (r) => if \"$node\" != \"*\" then\r\n                        r[\"node\"] == \"$node\"\r\n                    else\r\n                        r._measurement != \"\",\r\n      )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({r with device: strings.joinStr(arr: [r[\"node\"], r[\"device\"], r[\"varkey\"]], v: \"-\")}))\r\n  |> yield(name: \"last\")",
       "select": [
        [
         { "params": [ "dat_stat" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Pump",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "/$node/",
       "query": "import \"strings\"\r\nfrom(bucket: \"$bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"varkey\"] == \"stat\" or r[\"varkey\"] == \"pump\")\r\n  |> filter(\r\n          fn: (r) => if \"$node\" != \"*\" then\r\n                        r[\"node\"] == \"$node\"\r\n                    else\r\n                        r._measurement != \"\",\r\n      )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({r with device: strings.joinStr(arr: [r[\"node\"], r[\"device\"], r[\"varkey\"]], v: \"-\")}))\r\n  |> yield(name: \"last\")",
       "select": [
        [
         { "params": [ "dat_pump" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Tap Flow Rate",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "flowlpm" } },
     "targets": [
      {
       "alias": "DHW Flow Rate",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "/$node/",
       "query": "import \"strings\"\r\nfrom(bucket: \"$bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"varkey\"] == \"fC\")\r\n  |> filter(\r\n          fn: (r) => if \"$node\" != \"*\" then\r\n                        r[\"node\"] == \"$node\"\r\n                    else\r\n                        r._measurement != \"\",\r\n      )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({r with device: strings.joinStr(arr: [r[\"node\"], r[\"device\"], r[\"varkey\"]], v: \"-\")}))\r\n  |> yield(name: \"last\")",
       "select": [
        [
         { "params": [ "dat_fC" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "CH Stepper Valve Position",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "/ 270" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "/$node/",
       "query": "import \"strings\"\r\nfrom(bucket: \"$bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"varkey\"] == \"xCH\")\r\n  |> filter(\r\n          fn: (r) => if \"$node\" != \"*\" then\r\n                        r[\"node\"] == \"$node\"\r\n                    else\r\n                        r._measurement != \"\",\r\n      )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({r with device: strings.joinStr(arr: [r[\"node\"], r[\"device\"], r[\"varkey\"]], v: \"-\")}))\r\n  |> yield(name: \"last\")",
       "select": [
        [
         { "params": [ "dat_xCH" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "DHW Stepper Valve Position",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "/ 270" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "/$node/",
       "query": "import \"strings\"\r\nfrom(bucket: \"$bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"varkey\"] == \"xDHW\")\r\n  |> filter(\r\n          fn: (r) => if \"$node\" != \"*\" then\r\n                        r[\"node\"] == \"$node\"\r\n                    else\r\n                        r._measurement != \"\",\r\n      )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({r with device: strings.joinStr(arr: [r[\"node\"], r[\"device\"], r[\"varkey\"]], v: \"-\")}))\r\n  |> yield(name: \"last\")",
       "select": [
        [
         { "params": [ "dat_xDHW" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "System Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Data",
     "type": "table",
     "gridPos": { "h": 18, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "rawSql": "SELECT t1.varkey, t2.title, t1.value FROM readings t1\r\n  INNER JOIN fields t2 ON t1.varkey = t2.varkey AND t1.vargroup = t2.vargroup\r\n  WHERE t1.vargroup = 'system' AND t1.node = '$node' AND (t1.device = '$HIU' OR t1.device = '$node')"
      }
     ]
    },
    {
     "title": "Settings",
     "type": "table",
     "gridPos": { "h": 18, "w": 12, "x": 12, "y": 25 },
     "targets": [
      {
       "rawSql": "SELECT t1.varkey, t2.title, t1.value, t2.units FROM readings t1\r\n  INNER JOIN fields t2 ON t1.varkey = t2.varkey AND t1.vargroup = t2.vargroup\r\n  WHERE t1.vargroup = 'settings' AND t1.node = '$node' AND t1.device = '$HIU'"
      }
     ]
    }
   ]
  },
  {
   "title": "Operational Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "General Data",
     "type": "table",
     "gridPos": { "h": 18, "w": 12, "x": 0, "y": 22 },
     "targets": [
      {
       "rawSql": "SELECT t1.varkey, t2.title, t1.value, t2.units FROM readings t1\r\n  INNER JOIN fields t2 ON t1.varkey = t2.varkey AND t1.vargroup = t2.vargroup\r\n  WHERE t1.vargroup = 'dat' AND t1.node = '$node' AND (t1.device = '$HIU' OR t1.device = '$node')"
      }
     ]
    },
    {
     "title": "Stastistics",
     "type": "table",
     "gridPos": { "h": 18, "w": 12, "x": 12, "y": 22 },
     "targets": [
      {
       "rawSql": "SELECT t1.varkey, t2.title, t1.value, t2.units FROM readings t1\r\n  INNER JOIN fields t2 ON t1.varkey = t2.varkey AND t1.vargroup = t2.vargroup\r\n  WHERE t1.vargroup = 'stat' AND t1.node = '$node' AND (t1.device = '$HIU' OR t1.device = '$node')"
      }
     ]
    }
   ]
  },
  {
   "title": "Documentation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    { "type": "ryantxu-ajax-panel", "gridPos": { "h": 20, "w": 24, "x": 0, "y": 33 } }
   ]
  },
  {
   "title": "Experimental",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "DHW Temperatures",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT t1.varkey, t2.title, t1.value::numeric, t2.units FROM readings t1\r\n  INNER JOIN fields t2 ON t1.varkey = t2.varkey AND t1.vargroup = t2.vargroup\r\n  WHERE (t1.varkey = 'tCo' OR t1.varkey = 'tHoDHW' OR t1.varkey = 'tDHWReturn') AND t1.node = '$node' AND t1.vargroup = 'dat' AND (t1.device = '$HIU' OR t1.device = 'dhw')\r\n  ORDER BY t1.varkey"
      }
     ]
    },
    {
     "title": "DHW Temperatures",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "WITH \r\ndhw1 AS (SELECT t1.node, t1.device, t1.vargroup, t1.varkey, t2.title, t1.value::numeric, t2.units FROM readings t1\r\n  INNER JOIN fields t2 ON t1.varkey = t2.varkey AND t1.vargroup = t2.vargroup\r\n  WHERE (t1.varkey = 'tCo') AND t1.node = '$node' AND t1.vargroup = 'dat' AND (t1.device = '$HIU' OR t1.device = 'dhw')\r\n  ORDER BY t1.varkey\r\n),\r\ndhw2 AS (SELECT d1.*, t3.value::numeric AS flowRate,\r\n       CASE WHEN t3.value::numeric=0 THEN 'white'\r\n            ELSE 'green'\r\n       END\r\n     FROM dhw1 d1 \r\n  INNER JOIN readings t3 ON d1.node = t3.node AND d1.device = t3.device AND d1.vargroup = t3.vargroup AND t3.varkey = 'fC'\r\n)\r\nSELECT * FROM dhw2;"
      },
      {
       "rawSql": "WITH \r\ndhw1 AS (SELECT t1.node, t1.device, t1.vargroup, t1.varkey, t2.title, t1.value::numeric, t2.units FROM readings t1\r\n  INNER JOIN fields t2 ON t1.varkey = t2.varkey AND t1.vargroup = t2.vargroup\r\n  WHERE (t1.varkey = 'tHoDHW') AND t1.node = '$node' AND t1.vargroup = 'dat' AND (t1.device = '$HIU' OR t1.device = 'dhw')\r\n  ORDER BY t1.varkey\r\n),\r\ndhw2 AS (SELECT d1.*, t3.value::numeric AS flowRate,\r\n       CASE WHEN t3.value::numeric<6 THEN 'white'\r\n            ELSE 'green'\r\n       END\r\n     FROM dhw1 d1 \r\n  INNER JOIN readings t3 ON d1.node = t3.node AND d1.device = t3.device AND d1.vargroup = t3.vargroup AND t3.varkey = 'xDHW'\r\n)\r\nSELECT * FROM dhw2;"
      },
      {
       "rawSql": "SELECT t1.varkey, t2.title, t1.value::numeric, t2.units FROM readings t1\r\n  INNER JOIN fields t2 ON t1.varkey = t2.varkey AND t1.vargroup = t2.vargroup\r\n  WHERE (t1.varkey = 'tDHWReturn') AND t1.node = '$node' AND t1.vargroup = 'dat' AND (t1.device = '$HIU' OR t1.device = 'dhw')\r\n  ORDER BY t1.varkey"
      }
     ]
    }
   ]
  }
 ]
}