{
 "title": "hiusqba1",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "type": "marcuscalidus-svg-panel",
   "gridPos": { "h": 12, "w": 16, "x": 0, "y": 0 },
   "format": "short",
   "targets": [
    {
     "query": "from(bucket: \"thechantry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"network\"] == \"thechantry\")\r\n  |> filter(fn: (r) => r[\"vargroup\"] == \"dat\") \r\n  |> last()\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"thechantry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"network\"] == \"thechantry\")\r\n  |> filter(fn: (r) => r[\"vargroup\"] == \"dat\") \r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "System Data",
   "type": "table",
   "gridPos": { "h": 24, "w": 8, "x": 0, "y": 12 },
   "targets": [
    {
     "query": "from(bucket: \"thechantry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"network\"] == \"thechantry\")\r\n  |> filter(fn: (r) => r[\"vargroup\"] == \"system\") \r\n  |> last()\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Operational Data",
   "type": "table",
   "gridPos": { "h": 15, "w": 7, "x": 8, "y": 12 },
   "targets": [
    {
     "query": "from(bucket: \"thechantry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"network\"] == \"thechantry\")\r\n  |> filter(fn: (r) => r[\"vargroup\"] == \"dat\") \r\n  |> last()\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Settings",
   "type": "table",
   "gridPos": { "h": 24, "w": 9, "x": 15, "y": 12 },
   "targets": [
    {
     "query": "from(bucket: \"thechantry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"network\"] == \"thechantry\")\r\n  |> filter(fn: (r) => r[\"vargroup\"] == \"settings\") \r\n  |> last()\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Operational Data",
   "type": "table",
   "gridPos": { "h": 15, "w": 7, "x": 15, "y": 36 },
   "targets": [
    {
     "query": "from(bucket: \"thechantry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"network\"] == \"thechantry\")\r\n  |> filter(fn: (r) => r[\"vargroup\"] == \"dat\") \r\n  |> last()\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  }
 ]
}